spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nc_clothes_1
    username: postgres
    password: Bana54321bana3024
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

